apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: multi-platform-controller
resources:
  - namespace.yaml
  - deployment.yaml
  - sa.yaml
  - role.yaml
  - role-binding.yaml
  - provision-shared-host.yaml
  - clean-shared-host.yaml
  - openshift-specific-rbac.yaml
  - update-host.yaml
  - metricservice.yaml
patches:
  - target:
      kind: ClusterRole
      name: multi-platform-controller
    patch: |-
      - op: add
        path: "/metadata/labels"
        value: {"rbac.authorization.k8s.io/aggregate-to-edit": "true"}
