---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multi-platform-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-platform-controller
subjects:
  - kind: ServiceAccount
    name: multi-platform-controller
    namespace: multi-platform-controller
